package Modelo;
// Generated 12/10/2017 08:19:22 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idproducto;
     private Garantia garantia;
     private String nombre;
     private String codigo;
     private int cantidad;
     private BigDecimal costo;
     private BigDecimal precio;
     private BigDecimal utilidad;
     private String espef;
     private Date fechaIng;
     private byte servicio;
     private Set ventas = new HashSet(0);

    public Producto() {
    }

	
    public Producto(Garantia garantia, String nombre, int cantidad, BigDecimal costo, BigDecimal precio, String espef, Date fechaIng, byte servicio) {
        this.garantia = garantia;
        this.nombre = nombre;
        this.cantidad = cantidad;
        this.costo = costo;
        this.precio = precio;
        this.espef = espef;
        this.fechaIng = fechaIng;
        this.servicio = servicio;
    }
    public Producto(Garantia garantia, String nombre, String codigo, int cantidad, BigDecimal costo, BigDecimal precio, BigDecimal utilidad, String espef, Date fechaIng, byte servicio, Set ventas) {
       this.garantia = garantia;
       this.nombre = nombre;
       this.codigo = codigo;
       this.cantidad = cantidad;
       this.costo = costo;
       this.precio = precio;
       this.utilidad = utilidad;
       this.espef = espef;
       this.fechaIng = fechaIng;
       this.servicio = servicio;
       this.ventas = ventas;
    }
   
    public Integer getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(Integer idproducto) {
        this.idproducto = idproducto;
    }
    public Garantia getGarantia() {
        return this.garantia;
    }
    
    public void setGarantia(Garantia garantia) {
        this.garantia = garantia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getCosto() {
        return this.costo;
    }
    
    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public BigDecimal getUtilidad() {
        return this.utilidad;
    }
    
    public void setUtilidad(BigDecimal utilidad) {
        this.utilidad = utilidad;
    }
    public String getEspef() {
        return this.espef;
    }
    
    public void setEspef(String espef) {
        this.espef = espef;
    }
    public Date getFechaIng() {
        return this.fechaIng;
    }
    
    public void setFechaIng(Date fechaIng) {
        this.fechaIng = fechaIng;
    }
    public byte getServicio() {
        return this.servicio;
    }
    
    public void setServicio(byte servicio) {
        this.servicio = servicio;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


